import * as fs from 'fs';
import * as path from 'path';
import { CanvAppsConfig, PWAConfig } from '../config';

/**
 * Handles Progressive Web App (PWA) automated asset generation:
 * - Dynamic web app manifest.json
 * - Offline-first Service Worker (sw.js)
 * - HTML metadata and registration script injection
 */
export class PWATargetBuilder {
  public static async process(config: CanvAppsConfig, outputDir: string): Promise<void> {
    const pwa = config.pwa ?? {};
    console.log(`📱 [CanvApps CLI]: Generating PWA metadata and offline Service Worker for "${config.title || 'CanvApps App'}"...`);

    // 1. Generate web manifest
    const manifest = this.generateManifest(config, pwa);
    const manifestPath = path.join(outputDir, 'manifest.json');
    fs.writeFileSync(manifestPath, JSON.stringify(manifest, null, 2), 'utf-8');
    console.log(`  ✓ Generated: ${manifestPath}`);

    // 2. Generate Service Worker (sw.js)
    const swContent = this.generateServiceWorker(pwa);
    const swPath = path.join(outputDir, 'sw.js');
    fs.writeFileSync(swPath, swContent, 'utf-8');
    console.log(`  ✓ Generated: ${swPath}`);

    // 3. Inject PWA headers into index.html
    const indexPath = path.join(outputDir, 'index.html');
    if (fs.existsSync(indexPath)) {
      let html = fs.readFileSync(indexPath, 'utf-8');

      const pwaMetaTags = `
    <!-- CanvApps PWA Metadata -->
    <link rel="manifest" href="./manifest.json" />
    <meta name="theme-color" content="${pwa.themeColor || '#0f172a'}" />
    <meta name="mobile-web-app-capable" content="yes" />
    <meta name="apple-mobile-web-app-capable" content="yes" />
    <meta name="apple-mobile-web-app-status-bar-style" content="black-translucent" />
    <meta name="apple-mobile-web-app-title" content="${pwa.shortName || config.title || 'CanvApps'}" />
    <script>
      if ('serviceWorker' in navigator) {
        window.addEventListener('load', () => {
          navigator.serviceWorker.register('./sw.js').then((reg) => {
            console.log('[CanvApps PWA]: Service Worker registered with scope:', reg.scope);
          }).catch((err) => {
            console.warn('[CanvApps PWA]: Service Worker registration failed:', err);
          });
        });
      }
    </script>
`;

      html = html.replace('</head>', `${pwaMetaTags}\n  </head>`);
      fs.writeFileSync(indexPath, html, 'utf-8');
      console.log(`  ✓ Injected PWA tags and Service Worker register script into: ${indexPath}`);
    }
  }

  private static generateManifest(config: CanvAppsConfig, pwa: PWAConfig): Record<string, any> {
    return {
      name: pwa.name || config.title || 'CanvApps Application',
      short_name: pwa.shortName || config.title || 'CanvApps',
      description: pwa.description || 'High-performance Canvas UI Application',
      start_url: pwa.startUrl || './index.html',
      display: pwa.display || 'standalone',
      background_color: pwa.backgroundColor || '#0f172a',
      theme_color: pwa.themeColor || '#0f172a',
      orientation: pwa.orientation || 'any',
      icons: pwa.icons || [
        {
          src: './favicon.svg',
          sizes: 'any',
          type: 'image/svg+xml',
          purpose: 'any',
        },
        {
          src: './icon.png',
          sizes: '256x256',
          type: 'image/png',
          purpose: 'any maskable',
        },
      ],
    };
  }

  private static generateServiceWorker(_pwa: PWAConfig): string {
    const cacheName = `canvapps-pwa-v${Date.now()}`;
    return `
/**
 * CanvApps Progressive Web App Service Worker
 * Auto-generated by CanvApps CLI.
 */

const CACHE_NAME = '${cacheName}';
const ASSETS_TO_CACHE = [
  './',
  './index.html',
  './manifest.json',
];

self.addEventListener('install', (event) => {
  event.waitUntil(
    caches.open(CACHE_NAME).then((cache) => {
      console.log('[CanvApps SW]: Pre-caching core shell assets...');
      return cache.addAll(ASSETS_TO_CACHE);
    }).then(() => self.skipWaiting())
  );
});

self.addEventListener('activate', (event) => {
  event.waitUntil(
    caches.keys().then((keys) => {
      return Promise.all(
        keys.map((key) => {
          if (key !== CACHE_NAME) {
            console.log('[CanvApps SW]: Removing legacy cache:', key);
            return caches.delete(key);
          }
        })
      );
    }).then(() => self.clients.claim())
  );
});

self.addEventListener('fetch', (event) => {
  if (event.request.method !== 'GET') {
    return;
  }

  event.respondWith(
    caches.match(event.request).then((cachedResponse) => {
      if (cachedResponse) {
        return cachedResponse;
      }
      return fetch(event.request).then((networkResponse) => {
        if (!networkResponse || networkResponse.status !== 200 || networkResponse.type !== 'basic') {
          return networkResponse;
        }
        const responseToCache = networkResponse.clone();
        caches.open(CACHE_NAME).then((cache) => {
          cache.put(event.request, responseToCache);
        });
        return networkResponse;
      }).catch(() => {
        // Fallback to cached index for navigation
        if (event.request.mode === 'navigate') {
          return caches.match('./index.html');
        }
      });
    })
  );
});
`.trim();
  }
}
