import * as path from 'path';
import * as fs from 'fs';
import { build as viteBuild } from 'vite';
import { CanvAppsConfig } from './config';
import { SPATargetBuilder } from './targets/spa';
import { PWATargetBuilder } from './targets/pwa';
import { CapacitorTargetBuilder } from './targets/capacitor';
import { canvappsPlugin } from '../compiler/vitePlugin';
import { compileCVS } from '../compiler/transformer';

/**
 * Master multi-target build orchestrator for CanvApps.
 */
export class CLIBuilder {
  /**
   * Executes the full multi-target build pipeline based on `canvapps.config.ts`.
   */
  public static async build(configPath?: string): Promise<void> {
    console.log(`\n📦 ============================================`);
    console.log(`🚀 [CanvApps Multi-Target Build Orchestrator]`);
    console.log(`============================================\n`);

    const cwd = process.cwd();
    const resolvedConfigPath = configPath
      ? path.resolve(cwd, configPath)
      : path.resolve(cwd, 'canvapps.config.ts');

    const config = await this.loadConfig(resolvedConfigPath);
    const target = config.target || 'SPA';
    const outputDir = path.resolve(cwd, config.outDir || 'dist-app');

    console.log(`🎯 Target: [${target}]`);
    console.log(`📁 Output Directory: ${outputDir}\n`);

    // 1. Execute Vite Application Bundling
    console.log(`⚡ [Step 1/2]: Compiling Canvas Application & .cvs Components with Vite...`);
    await viteBuild({
      configFile: false,
      root: cwd,
      base: './',
      plugins: [canvappsPlugin()],
      build: {
        outDir: outputDir,
        emptyOutDir: true,
        minify: 'esbuild',
        sourcemap: false,
      },
      resolve: {
        alias: {
          '@canvapps': path.resolve(cwd, 'CanvApps/index.ts'),
        },
      },
    });
    console.log(`  ✓ Application build succeeded!\n`);

    // 2. Execute Target-Specific Post-Processing
    console.log(`🛠️  [Step 2/2]: Running Post-Processing for Target: ${target}...`);
    switch (target) {
      case 'PWA':
        await PWATargetBuilder.process(config, outputDir);
        break;
      case 'CAPACITOR':
        await CapacitorTargetBuilder.process(config, outputDir);
        break;
      case 'SPA':
      default:
        await SPATargetBuilder.process(config, outputDir);
        break;
    }

    console.log(`\n✨ [CanvApps Build Completed Successfully for Target: ${target}] 🎉\n`);
  }

  /**
   * Builds an unminified, inspectable preview of compiled .cvs components and application bundle.
   *
   * Designed for code review, open-source verification, and architecture demonstration.
   */
  public static async buildPreviewCode(outDirectory = 'preview-code'): Promise<void> {
    console.log(`\n🔍 ========================================================`);
    console.log(`🔬 [CanvApps Preview-Code & Syntax Inspection Builder]`);
    console.log(`========================================================\n`);

    const cwd = process.cwd();
    const previewDir = path.resolve(cwd, outDirectory);
    const compiledDir = path.resolve(previewDir, 'compiled-components');
    const bundleDir = path.resolve(previewDir, 'bundle');

    // Clean & create directories
    if (fs.existsSync(previewDir)) {
      fs.rmSync(previewDir, { recursive: true, force: true });
    }
    fs.mkdirSync(compiledDir, { recursive: true });
    fs.mkdirSync(bundleDir, { recursive: true });

    console.log(`📁 Target Inspection Directory: ${previewDir}\n`);

    // 1. Scan and transform all .cvs files into clean, readable TypeScript
    console.log(`📄 [Step 1/3]: Transforming .cvs Single-File Components to TypeScript...`);
    const srcDir = path.resolve(cwd, 'src');
    const cvsFiles = this.findFilesByExt(srcDir, '.cvs');

    for (const file of cvsFiles) {
      const relative = path.relative(srcDir, file);
      const content = fs.readFileSync(file, 'utf-8');
      const { code } = compileCVS(content);

      const targetPath = path.resolve(compiledDir, `${relative}.ts`);
      fs.mkdirSync(path.dirname(targetPath), { recursive: true });

      const header = `/**\n * Auto-generated by CanvApps SFC Compiler\n * Source: src/${relative}\n * \n * This file demonstrates how .cvs template tags, directives (@each, @if),\n * and dynamic bindings (:value, @click) are converted into pure TypeScript Canvas nodes\n * with zero Virtual DOM overhead.\n */\n\n`;
      fs.writeFileSync(targetPath, header + code, 'utf-8');
      console.log(`  ✓ Transformed: src/${relative} -> preview-code/compiled-components/${relative}.ts`);
    }

    // 2. Build unminified, readable application bundle
    console.log(`\n⚡ [Step 2/3]: Bundling Unminified Application (minify: false)...`);
    await viteBuild({
      configFile: false,
      root: cwd,
      plugins: [canvappsPlugin()],
      build: {
        outDir: bundleDir,
        emptyOutDir: true,
        minify: false,
        sourcemap: true,
        rollupOptions: {
          output: {
            entryFileNames: 'assets/[name].readable.js',
            chunkFileNames: 'assets/[name].readable.js',
            assetFileNames: 'assets/[name].[ext]',
          },
        },
      },
      resolve: {
        alias: {
          '@canvapps': path.resolve(cwd, 'CanvApps/index.ts'),
        },
      },
    });
    console.log(`  ✓ Unminified bundle generated in: preview-code/bundle/`);

    // 3. Generate Inspection README Documentation
    console.log(`\n📝 [Step 3/3]: Generating Inspection & Architecture Guide...`);
    const readmeContent = `# CanvApps Architecture & Syntax Inspection Guide

Welcome to the **CanvApps Preview-Code** directory. This folder contains the **unminified, un-obfuscated** output of the CanvApps build process, specifically generated for developers, auditors, and contributors who want to inspect how the framework works internally.

---

## 📂 Directory Structure

\`\`\`
preview-code/
├── compiled-components/
│   └── App.cvs.ts             # Direct TypeScript output of the .cvs Single-File Component
├── bundle/
│   ├── index.html             # Application entry HTML
│   └── assets/
│       ├── index.readable.js  # Unminified, human-readable JavaScript bundle
│       └── index.readable.js.map
└── README.md                  # This architectural explanation
\`\`\`

---

## ⚡ How CanvApps Compiles .cvs Components

Unlike traditional web frameworks that convert templates into a Virtual DOM tree (which must be reconciled on every render), CanvApps transforms \`.cvs\` markup directly into **imperative Canvas node instantiations**:

### 1. Template Transformation
* \`<view width="100%" flexDirection="column">\` ➡️ \`new UIView({ width: "100%", flexDirection: "column" })\`
* \`<text fontSize="18" color="#0f172a">\` ➡️ \`new UIText("...", { fontSize: 18, color: "#0f172a" })\`
* \`<button label="Increment" @click="increment">\` ➡️ \`new UIButton("Increment", ...)\` with direct event binding.
* \`<input :value="taskInput.value" @submit="addMilestone">\` ➡️ \`new UIInput(...)\` with two-way Ghost DOM mirroring.

### 2. Direct Fine-Grained Signals (No VDOM Diffing)
Dynamic expressions like \`{{ cycleCount.value }}\` or \`:value="taskInput.value"\` are wrapped in micro-effects:
\`\`\`ts
effect(() => {
  textNode.setText(String(\`\${cycleCount.value} Total Cycles\`));
});
\`\`\`
When \`cycleCount.value\` changes, **only that specific Canvas node** is marked dirty and redrawn on the next \`requestAnimationFrame\` pass.

### 3. Svelte-Style Iteration (\`@each\`)
\`\`\`html
<view @each="milestones.value as item, index">
  <text fontSize="13">• {{ item.text }}</text>
</view>
\`\`\`
compiles to an optimized container effect that repopulates Canvas child nodes reactively when the list array changes.

---

## 🚀 Running and Inspecting

To inspect the generated code:
1. Open \`preview-code/compiled-components/App.cvs.ts\` to see the direct TypeScript compiler output.
2. Open \`preview-code/bundle/assets/index.readable.js\` to see the readable bundled runtime.
`;

    fs.writeFileSync(path.resolve(previewDir, 'README.md'), readmeContent, 'utf-8');
    console.log(`  ✓ Generated: preview-code/README.md\n`);

    console.log(`✨ [CanvApps Preview-Code Build Completed Successfully!] 🔬`);
    console.log(`👉 Inspect the unminified code at: ${previewDir}\n`);
  }

  /**
   * Recursively finds files matching an extension.
   */
  private static findFilesByExt(dir: string, ext: string): string[] {
    const results: string[] = [];
    if (!fs.existsSync(dir)) return results;

    const entries = fs.readdirSync(dir, { withFileTypes: true });
    for (const entry of entries) {
      const fullPath = path.resolve(dir, entry.name);
      if (entry.isDirectory()) {
        results.push(...this.findFilesByExt(fullPath, ext));
      } else if (entry.isFile() && entry.name.endsWith(ext)) {
        results.push(fullPath);
      }
    }
    return results;
  }

  /**
   * Loads and parses canvapps.config.ts.
   */
  private static async loadConfig(configPath: string): Promise<CanvAppsConfig> {
    if (!fs.existsSync(configPath)) {
      console.warn(`⚠️ [CanvApps CLI]: No "canvapps.config.ts" found at ${configPath}. Using default SPA config.`);
      return {
        target: 'SPA',
        title: 'CanvApps Application',
        outDir: 'dist-app',
      };
    }

    try {
      // Dynamic import of the config module
      const imported = await import(configPath);
      return imported.default || imported;
    } catch (err: any) {
      console.warn(`⚠️ [CanvApps CLI]: Error reading config file: ${err.message}. Falling back to default.`);
      return {
        target: 'SPA',
        title: 'CanvApps Application',
        outDir: 'dist-app',
      };
    }
  }
}
